---
kind: pipeline
type: docker
name: deploy

clone:
  disable: true

steps:
- name: test repository
  image: alpine/git
  commands:
  - curl 'https://gitea.catbit.eu/bogdan/jellyfin-plugin-tunein.git' --head --insecure

- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: clean
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet clean

- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build --configuration Release

- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet test --configuration Release

- name: bundle
  image: alpine/git
  commands:
  - apk add zip
  - mkdir -p publish
  - zip -j publish/tunein_$$(git describe --tags --abbrev=0).zip ./Jellyfin.Plugin.TuneIn/bin/Release/net*/*.dll
  - echo 'checksum'
  - md5sum publish/tunein_*.zip | awk '{print $1, substr($2,9)}'
  when:
    target:
    - production

- name: upload
  image: alpine/git
  environment:
    WEBDAV_PASSWORD:
      from_secret: SFTPGO_WEBDAV_JELLYFIN_PASSWORD
    WEBDAV_USERNAME:
      from_secret: SFTPGO_WEBDAV_JELLYFIN_USER
    WEBDAV_URL: https://webdav.sftpgo.home
  commands:
  - curl "$WEBDAV_URL/jellyfin/repository/plugins/" --user "$WEBDAV_PASSWORD:$WEBDAV_USERNAME" --insecure -T publish/*.zip
  when:
    target:
    - production
