---
kind: pipeline
type: docker
name: deploy

steps:
- name: clean
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet clean

- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build --configuration Release

- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet test --configuration Release

- name: bundle
  image: alpine/git
  commands:
  - apk add zip
  - mkdir -p publish
  - zip -j publish/tunein_$DRONE_TAG.zip ./Jellyfin.Plugin.TuneIn/bin/Release/net*/*.dll
  when:
    target:
    - production

- name: upload
  image: plugins/s3
  environment:
    UPLOAD_URL:
      from_secret: tunein_upload_url
    UPLOAD_BUCKET:
      from_secret: tunein_upload_bucket
    UPLOAD_ACCESS_KEY:
      from_secret: tunein_upload_access_key
    UPLOAD_SECRET_KEY:
      from_secret: tunein_upload_secret_key
    UPLOAD_TARGET:
      from_secret: tunein_upload_target
  settings:
    endpoint: $UPLOAD_URL
    bucket: $UPLOAD_BUCKET
    access_key: $UPLOAD_ACCESS_KEY
    secret_key: $UPLOAD_SECRET_KEY
    target: $UPLOAD_TARGET
    source: publish/*.zip
  when:
    target:
    - production
