---
kind: pipeline
type: docker
name: deploy

steps:

- name: clean
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet clean

- name: restore
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet restore

- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build

- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet test

