---
kind: pipeline
type: docker
name: deploy

steps:
- name: fetch
  commands:
  - git fetch --tags

- name: clean
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet clean

- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build --configuration Release

- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet test --configuration Release

- name: bundle
  image: alpine/git
  commands:
  - apk add zip
  - mkdir -p publish
  - zip -j publish/tunein_$$(git describe --tags).zip ./Jellyfin.Plugin.TuneIn/bin/Release/net*/*.dll
  when:
    target:
    - production

- name: upload
  image: plugins/s3
  settings:
    endpoint:
      from_secret: minio_url
    bucket:
      from_secret: tunein_upload_bucket
    access_key:
      from_secret: tunein_upload_access_key
    secret_key:
      from_secret: tunein_upload_secret_key
    target:
      from_secret: tunein_upload_target
    path_style: true
    source: publish/*.zip
    strip_prefix: publish/
  when:
    target:
    - production
